### ISSUE TITLE
nbib support

### ISSUE THREAD

**Issue by holub008** [MrTango/rispy#24]
I would like to gauge interest in supporting the [nbib format](https://pubmed.ncbi.nlm.nih.gov/help/#pubmed-format) (most notably Pubmed's citation manager export format) in `rispy`. The formats are very similar, and I have imagine the settings in which `rispy` users want to handle ris files, they equally would want to handle nbib.

**Comment by holub008** [comment]
I'm happy to do the work here, and will create a tangible plan of action / API changes if we agree on the addition.

**Comment by shapiromatron** [comment]
Sure, I'd be interested for sure.  I think Pubmed just got rid of RIS exports in favor of this format, is that right?  https://www.nlm.nih.gov/pubs/techbull/ma20/ma20_pubmed_updated.html

**Comment by holub008** [comment]
Great. It seems like we should leave the `parse` API alone by just adding a new `RisImplementation`. There will be several complexities in adapting the `Base` ris parser and the output API (identified below). I'd like to hear any thoughts about the below, particularly if the implementation should be separate from the `Base` parser, or maybe even moved to a new package, if the API is too different. 

## Nested tags
We'll need a way to conditionally map from a tag type to potentially many mapping names, using the line content  (instead of just building a list). For example, the AID (article id) tag from pubmed looks like:
```
AID - CDTCNSND-EPUB-20130227-10 [pii]
AID - 10.2174/1871527311312050015 [doi]
```

We'd want to map the first line to a new 'pii' name, and the second to 'doi'. 

### My thoughts
Add "remapping" functions to the `Base` parser. For implementations other than nbib, these will be empty. For the nbib implementation, these functions will be baked in and**not** be configurable via API.

## Line endings
There's no `ER` tag or similar in nbib. Just a newline which terminates the record. 

### My thoughts
This one's pretty easy to add to the `Base` parser. E.g. if `END_TAG` is null, and an empty line is encountered, start a new record. 

## Arbitrary choices in our default mapping
I'd like to maintain the "API" as much as possible by having the keys of the default tag mapping for nbib match that of ris. However, nbib will frequently contain several versions of the same data, which map to the same concept. Or, will allow for `ListType` tags that RIS generally does not. For example, here's an author list:
```
FAU - Prabhakaran, Shyam
AU  - Prabhakaran S
AD  - Department of Neurology, Northwestern University Feinberg School of Medicine, 
      Chicago, Illinois.
FAU - Ruff, Ilana
AU  - Ruff I
AD  - Department of Neurology, Northwestern University Feinberg School of Medicine, 
      Chicago, Illinois.
FAU - Bernstein, Richard A
AU  - Bernstein RA
AD  - Department of Neurology, Northwestern University Feinberg School of Medicine, 
      Chicago, Illinois.
``` 
The difficulties are:

- We have two tags for each author `FAU` and `AU`, which both represent the `author` concept, with different content. Which would we choose? 
- `AD` (mapped to `author_address`) will need to be a list type even though the ris mapping only provides a string. We could make an arbitrary choice, like only using first author, or we could join them all together.

### My thoughts
This is an inherent complexity. I think we'll just have to make best judgement for the default, on a case by case basis. (e.g. use `AU` for `authors` and provide a new `authors_full_name` field).

**Comment by holub008** [comment]
RE "Nested Tags", here are a couple other examples to illustrate the level of generality needed here:

```
IS  - 1538-3598 (Electronic)
IS  - 0098-7484 (Linking)
```

```
RN  - 0 (Fibrinolytic Agents)
RN  - EC 3.4.21.68 (Tissue Plasminogen Activator)
```

```
PHST- 2015/04/15 06:00 [entrez]
PHST- 2015/04/15 06:00 [pubmed]
PHST- 2015/04/29 06:00 [medline]
```

To be clear, I'm not sure we even want to bother supporting all of these (e.g. `PHST`). The argument could be made that PubMed's API is more appropriate for getting article metadata that barely relates to citation

**Comment by holub008** [comment]
I decided to make this a [separate package](https://github.com/holub008/nbib), which is now `nbib` on PyPi. There was enough API change (in the output format) and internal complexity (e.g. properly structuring author information or MeSH tags), that I didn't think it would play nicely with `rispy`.

Thanks!

**Comment by shapiromatron** [comment]
Makes sense to me, this does seem like a different file format for a number of reasons. Congrats on the new package!  If you'd like to submit a PR on this package to reference the other package for parsing `nbib`, that works for me.

**Comment by holub008** [comment]
Sure! Where do you think that belongs?

**Comment by shapiromatron** [comment]
hey, sorry I never replied to you. Could you add a new section on the `README.rst` for alternative implementations for RIS-like files? That way hopefully we can help promote your package.

**Comment by holub008** [comment]
Thanks Andy, PR is up.
