### ISSUE TITLE
Handling Extraneous/Malformed Data 

### ISSUE THREAD

**Issue by ShreyRavi** [MrTango/rispy#30]
The `.RIS` export format from the [Cochrane Library](https://en.wikipedia.org/wiki/Cochrane_Library) medical database inserts some meta information before every entry as shown below. This causes `rispy` to throw an `OSError` due to a non `TY` tag, since the first line is the meta information (ex. "Record #1 of 784"), as pointed out by @holub008 .

### Excerpt Generated From [Cochrane](https://www.cochranelibrary.com/search):
```
Record #1 of 784
Provider: John Wiley & Sons, Ltd
Content: text/plain; charset="UTF-8"

TY  -  JOUR
...omitted here...
ER  -  

Record #2 of 784
Provider: John Wiley & Sons, Ltd
Content: text/plain; charset="UTF-8"

TY  -  JOUR
...omitted here...
ER  -  
```

## Error Output:
```
Traceback (most recent call last):
  File "issue.py", line 18, in <module>
    entries = rispy.load(cochrane_file)
  File "/home/st/.local/lib/python3.8/site-packages/rispy/parser.py", line 202, in load
    return list(loads(file.read(), mapping, implementation))
  File "/home/st/.local/lib/python3.8/site-packages/rispy/parser.py", line 237, in loads
    return list(Ris(filelines, mapping).parse())
  File "/home/st/.local/lib/python3.8/site-packages/rispy/parser.py", line 58, in parse
    yield self.parse_other(line, line_number)
  File "/home/st/.local/lib/python3.8/site-packages/rispy/parser.py", line 101, in parse_other
    raise IOError(f"Expected start tag in line {line_number}:\n {line}")
OSError: Expected start tag in line 0:
 Record #1 of 784
```

This error fails to appear when the meta information before the `TY` tag is removed.

## Error Reproduction
Note: `.ris` files to reproduce error can be found if going to [Cochrane ](https://www.cochranelibrary.com/search) site and attempting to export any result and passing into `rispy`. Same issue occurs from `.ris` files in some [Embase](https://en.wikipedia.org/wiki/Embase) citation exports.

## Why Should This Be Fixed?
While it could be possible for the end user to develop format pre-processing scripts before passing into `rispy`, it can be an even better feature to have an option in `rispy` to allow the user to remove any unrelated meta information not contained within the `TY` and `ER` tags, rather than a relatively vague, unintuitive error.

**Comment by holub008** [comment]
Disclosure: Shrey and I are coworkers.

I want to emphasize that Embase/Ovid also produces malformed RIS by default as well. I've attached an example of that. Users can uncheck certain options to remove the non-formatted data, but it's pretty unideal to put that expectation on our users.

We'd like to discuss options for cleaning up malformed data in between records. A couple proposals:

- a preprocessing function (outside the load functions) that aggressively removes non-tag-like data.
- a parameter to the load functions that allows non-tag data between records to be silently ignored.

Interested to hear your thoughts!

**Comment by shapiromatron** [comment]
What do you think about adding a `strict: bool = True` argument to the `load/loads`?

**Comment by ShreyRavi** [comment]
Submitted pull request: https://github.com/MrTango/rispy/pull/31 with implementation + test.

**Comment by holub008** [comment]
@shapiromatron Thanks for the speedy process here, much appreciated! We're not in a rush to get this, but for our timeline, when can we expect next release?

**Comment by shapiromatron** [comment]
Done; version 0.6.0 released: https://pypi.org/project/rispy/0.6.0/
