### ISSUE TITLE
Is readris() function still working?

### ISSUE THREAD

**Issue by MonikaBarget** [MrTango/rispy#35]
I was directed here from [RISparser on Pypi.org]( https://pypi.org/project/RISparser/) and am a bit confused about the documentation. On the Pypi page, the example shown uses the `readris()` function to read the data, but I could not get this to work at all (cf. [my issue on Stackoverflow](https://stackoverflow.com/questions/66885960/problems-with-readris-when-using-risparser-in-python-3)). 

Now I am wondering if `readris()` or even the entire RISparser package are still working as it seems to have been replaced by `rispy()` in the examples shown here on GITHUB.

**Comment by shapiromatron** [comment]
That's correct. RISparser was version 0.4 and below, and we renamed and rebranded to rispy in version 0.5.  The API for rispy is much cleaner and mirrors the python json library from the stdlib, which many people are familiar with.

For more details, read the changelog: https://github.com/MrTango/rispy/blob/master/HISTORY.rst#v05-2020-02-21

**Comment by MonikaBarget** [comment]
Ah, no wonder I got stuck! Could you, please, make sure that the RISparser page is updated accordingly? I didn't spot any info that there's a more recent version.

**Comment by shapiromatron** [comment]
That's a good idea. We minted a new version so the readme now redirects to rispy:
https://pypi.org/project/RISparser/0.4.4/

<img width="925" alt="Screen Shot 2021-04-01 at 3 54 03 PM" src="https://user-images.githubusercontent.com/999952/113346975-85dcf480-9302-11eb-9cef-08562c3d45c0.png">
