### ISSUE TITLE
Encodings support

### ISSUE THREAD

**Issue by ottomattas** [MrTango/rispy#38]
Hi. I'm wondering how is [rispy](https://pypi.org/project/rispy/) handling encodings besides the common UTF-8. Right now, I am getting stuck with Cyrillic (see [ris.zip](https://github.com/MrTango/rispy/files/6466215/ris.zip)) but I can imagine that other charsets can fall short here as well. As we are supporting a growing user base with rispy, we are starting to get questions about these "non-standard" encodings. 

Can you elaborate on your vision and the current status? (e.g Are you looking to plan on supporting a variety of encodings in the future?) Thanks in advance.

**Comment by scott-8** [comment]
In the issue you mentioned, the test file actually looks like it's UTF-8, but it's not a properly formatted RIS file (see `Expected start tag in line 0` at the top`). Rispy is producing an `IOError` and it's being caught [here](https://github.com/asreview/asreview/blob/ac7e72d555851c417aacdb6f20551f4448c99c20/asreview/io/ris_reader.py#L68). It doesn't look like an encoding issue.

Regarding encoding, rispy uses strings internally which are Unicode by default. The user controls the encoding when using a file-like object, and there shouldn't be any limitations from rispy. One addition that could be made would the ability to configure encoding when using a path as an input, which would be fairly trivial. Right now it uses the system default.

**Comment by ottomattas** [comment]
Thanks for the input! I will investigate further and will close this issue for now.
