### ISSUE TITLE
relicense from GPLv2 to MIT

### ISSUE THREAD

**Issue by shapiromatron** [MrTango/rispy#39]
I propose relicensing this project to MIT or another more permissive license.

For this change to occur, every contributor must agree to it. They are all listed below.

- [x] @MrTango
- [x] @shapiromatron
- [x] @sacabuche
- [x] @J535D165
- [x] @jiaola
- [x] @JoshAddington
- [x] @timflutre-perso
- [x] @holub008
- [x] @emilyzzz
- [x] @ShreyRavi
- [x] @scott-8
- [x] @KOLANICH

Other open-source projects which successfully relicensed:
- https://github.com/CloudburstMC/Nukkit/pull/1787
- https://github.com/Siphalor/mouse-wheelie/pull/99

**Comment by sacabuche** [comment]
I approve changing the license to MIT

**Comment by JoshAddington** [comment]
I approve changing the license to MIT

**Comment by scott-8** [comment]
I approve changing the license to MIT

**Comment by MrTango** [comment]
I approve changing the license to MIT

**Comment by ShreyRavi** [comment]
I approve changing the license to MIT

**Comment by timflutre-perso** [comment]
I approve changing the license to MIT

**Comment by holub008** [comment]
I approve changing the license to MIT

with great enthusiasm!

**Comment by emilyzzz** [comment]
I approve changing the license to MIT

**Comment by KOLANICH** [comment]
My contributions can be considered licensed under Unlicense

**Comment by shapiromatron** [comment]
> My contributions can be considered licensed under Unlicense

@KOLANICH Ok, I dont have a great understanding of how to dual license code in a repo. Is it ok if we use MIT? This is a very permissive license but it less ambiguous that Unlicense based on my understanding. If you're ok, could you please approve using the language specified?

**Comment by scott-8** [comment]
@shapiromatron if he has licensed his contributions under the Unlicense you can relicense their contributions without permission. Unilicense is basically public domain.

**Comment by shapiromatron** [comment]
> @shapiromatron if they have licensed their contributions under the Unlicense you can relicense them without permission. Unlicense is basically public domain. Dual licensing is not necessary here.

AFAIK that’s the US read but it’s ambiguous elsewhere such as Germany, @KOLANICH are you ok with this?

**Comment by KOLANICH** [comment]
"Just public domain" is ambigious in Germany. Unlicense is a kind of an ultra-permissive license. No more ambigious tham MIT is.

**Comment by shapiromatron** [comment]
Got it. Ok, so I take this as you're ok with us changing the license to MIT, is that correct @KOLANICH ? You're not a contributor yet but I'll be merging your PR #34 in shortly...

**Comment by KOLANICH** [comment]
>Ok, so I take this as you're ok with us changing the license to MIT, is that correct @KOLANICH ?

Unlicense allows relicensing. So OK.

**Comment by shapiromatron** [comment]
@jiaola sorry to bother you again, but could you please approve this change if you're ok with it?  We have everyone else in agreement ...

**Comment by shapiromatron** [comment]
@jiaola - please respond you're the last we haven't heard from; we see you're active on github so you should be receiving these messages right?

**Comment by jiaola** [comment]
Sorry for the late reply. I approve changing the license to MIT

**Comment by shapiromatron** [comment]
Thanks everyone! We have approval to relicense to MIT - I will do so in the upcoming release!
