### ISSUE TITLE
Only one URL is being imported

### ISSUE THREAD

**Issue by maxi07** [MrTango/rispy#47]
Hey there, I just noticed, that the reader can only read one UR item and the writer will only save on UR item from a .RIS entry.

**Comment by maxi07** [comment]
An example entry is:
TY  - JOUR
AU  - O'Connor, C
AU  - Kelly, S
TI  - Facilitating knowledge management through filtered big data: SME competitiveness in an agri-food sector
JF  - Journal of Knowledge Management
PB  - emerald.com
DO  - 10.1108/JKM-08-2016-0357
UR  - https://www.emerald.com/insight/content/doi/10.1108/JKM-08-2016-0357/full/html?fullSc=1
UR  - https://mural.maynoothuniversity.ie/11229/1/COC_Facilitating_2017.pdf
PY  - 2017///
AB  - … filtered big data within an agri… big data use, to enable SMEs to engage with big data and to impact positively on small business competitiveness. The big data of interest is that of big data …
M1  - Query date: 2022-09-25 18:25:59
M1  - 114 cites: https://scholar.google.com/scholar?cites=4934622460374198466&as_sdt=2005&sciodt=2007&hl=en
N1  - Cited By (since 2017): 114
ER  - 

where only the first URL from _UR_ is imported. The same goes for file_attachements1, where only one item will be read or written.

**Comment by shapiromatron** [comment]
That's correct; tags which are "list tags" are set in the `rispy.LIST_TYPE_TAGS` variable. You can override that list to include URLs if you need too; see example below:

```python
from io import StringIO
import rispy

text="""
TY  -  JOUR
AU  -  O'Connor, C
AU  -  Kelly, S
TI  -  Facilitating knowledge management through filtered big data: SME competitiveness in an agri-food sector
JF  -  Journal of Knowledge Management
PB  -  emerald.com
DO  -  10.1108/JKM-08-2016-0357
UR  -  https://www.emerald.com/insight/content/doi/10.1108/JKM-08-2016-0357/full/html?fullSc=1
UR  -  https://mural.maynoothuniversity.ie/11229/1/COC_Facilitating_2017.pdf
PY  -  2017///
AB  -  … filtered big data within an agri… big data use, to enable SMEs to engage with big data and to impact positively on small business competitiveness. The big data of interest is that of big data …
M1  -  Query date: 2022-09-25 18:25:59
M1  -  114 cites: https://scholar.google.com/scholar?cites=4934622460374198466&as_sdt=2005&sciodt=2007&hl=en
N1  -  Cited By (since 2017): 114
ER  -
"""
f = StringIO(text)

# set these values to also be list tags
rispy.LIST_TYPE_TAGS.extend(["UR", "M1"]

rispy.loads(text)
```

Is this a sufficient workaround?

**Comment by maxi07** [comment]
Thanks for the quick reply! Yes this fixed my issue.
**But** The main issue still persists, that if a RIS file has more than one entry in the __UR__ section, rispy will only take the first url and ignore the remaining ones, which can lead to data loss.

**Comment by J535D165** [comment]
Building a sloppy parser doesn't seem to be the way forward for me. 

Regarding the URL field: There might be an issue in rispy as the specification says that it could be one per tag ([specificationRIS.pdf](https://github.com/MrTango/rispy/files/9707795/Direct.Export.RIS.pdf)).

<img width="425" alt="image" src="https://user-images.githubusercontent.com/12981139/193846341-801a152b-7717-45e9-8418-717473d2119b.png">


**Side note:**

The API is pretty flexible nowadays, and you can build a parser in seconds. An alternative parser would be:

```python
import rispy

text="""
TY  -  JOUR
AU  -  O'Connor, C
AU  -  Kelly, S
TI  -  Facilitating knowledge management through filtered big data: SME competitiveness in an agri-food sector
JF  -  Journal of Knowledge Management
PB  -  emerald.com
DO  -  10.1108/JKM-08-2016-0357
UR  -  https://www.emerald.com/insight/content/doi/10.1108/JKM-08-2016-0357/full/html?fullSc=1
UR  -  https://mural.maynoothuniversity.ie/11229/1/COC_Facilitating_2017.pdf
PY  -  2017///
AB  -  … filtered big data within an agri… big data use, to enable SMEs to engage with big data and to impact positively on small business competitiveness. The big data of interest is that of big data …
M1  -  Query date: 2022-09-25 18:25:59
M1  -  114 cites: https://scholar.google.com/scholar?cites=4934622460374198466&as_sdt=2005&sciodt=2007&hl=en
N1  -  Cited By (since 2017): 114
ER  -
"""

class CustomRisParser(rispy.RisParser):
    DEFAULT_LIST_TAGS = rispy.LIST_TYPE_TAGS + ["UR", "M1"]

rispy.loads(text, implementation=CustomRisParser)
```

**Comment by shapiromatron** [comment]
Thanks! The spec seems ambiguous then; if URLs were semicolon delimited you'd expect a single tag. I propose we keep as-is with the ability to override as you suggest.

**Comment by maxi07** [comment]
The overwrite works as a solution for me, but I think this behavior should be marked clearly, as with the current state, you would lose your else without an overwrite.

**Comment by J535D165** [comment]
Yes, I don't like to lose information while the provider follows the specification. Any reason not to make it a list type (and parse the semicolon-separated values into a list)? This will be a breaking change, but rispy is still in beta. 

Off topic: maybe we should release a new version of the RIS specification (`openRIS`?) and sort issues like this out. No one seems to care anymore about the specification, while the number of users keeps increasing.
