### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by ccbogel** [MrTango/rispy#48]
I exported a bibliography from EndNote on Windows 10.

rispy version 0.7.1

  File "C:\Users\cc\AppData\Local\Programs\Python\Python310\lib\site-packages\rispy\parser.py", line 311, in load
    text = file.read_text(encoding=encoding) if isinstance(file, Path) else file.read()

  File "C:\Users\cc\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]

UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 150: character maps to <undefined>

In NotePad:
Using UTF-8 with BOM or just UTF-8 it did not load.
I then saved the file in ANSI format and it loaded OK (though of course some characters eg in Polish names changed to ANSI).

Out of interest it loaded fine on Ubuntu 22.04.

The problem file is attached:

[eeee.txt](https://github.com/MrTango/rispy/files/10026979/eeee.txt)

**Comment by ccbogel** [comment]
Fixed the error like this:
with open(filepath, 'r', encoding="utf-8", errors="surrogateescape") as ris_file:
            entries = rispy.load(ris_file)

**Comment by shapiromatron** [comment]
I think the current behavior is appropriate; there are too many possible encoding differences that may make it difficult to build a package that could handle them all. A more generic solution might be to just load a file into a string, and then pass that to the rispy parser as such:

```python
text = Path('eeee.txt').read_text(encoding="utf-8", errors="surrogateescape")
rispy.loads(text)
```
