### ISSUE TITLE
Bug in writing unknown_tags

### ISSUE THREAD

**Issue by simon-20** [MrTango/rispy#49]
Hi,

There appears to be a bug when writing unknown tags. When writing unknown tags, they are treated as single-line text entries, meaning that the resultant RIS file ends up with a line such as the following:

`UK  - defaultdict(<class 'list'>, {'ED': ['David M. Andrews (ed.)']})`

The issue is replicable with the `test-01.txt` file ([test-01.txt](https://github.com/MrTango/rispy/files/11653743/test-01.txt)) attached RIS file, and the `rispy-bug.txt` ([rispy-bug.txt](https://github.com/MrTango/rispy/files/11653769/rispy-bug.txt)) attached py file. 

The Python file illustrates the bug. It opens the file, saves the file, then opens it again, and attempts to treat the unknown tag (UK) entries in the same manner as any other entries, at which point a `TypeError` is thrown because a string exists where there should be a defaultdict.

I've modified `writer.py` to fix the issue, and will submit a pull request.

Simon

**Comment by shapiromatron** [comment]
Implemented by @simon-20 in #50
