### ISSUE TITLE
Ignore tags outside of a record

### ISSUE THREAD

**Issue by holub008** [MrTango/rispy#61]
We've had numerous users experience issues when importing RIS from Ovid. For whatever reason, it inserts a `C1` tag after the first record's `ER` (in addition to a bunch of non-tag lines, such as the search strategy). It's frustrating that Ovid/Embase is doing this, but it's a big enough platform that we're seeing users frequently encounter it. And, other software like EN/Zotero do successfully import files like this.

For privacy/copyright reasons, I won't attach any full examples, but it consistently looks like this:

```
1. 
TY  - JOUR
...
ER  -  

Link to the Ovid Full Text or citation: ...

C1  - Database: Embase <1980 to 2024 Week 25>

Search Strategy:

--------------------------------------------------------------------------------
...

2. 
TY  - JOUR
...
```

It would be great if `rispy` offered a mechanism to simply drop stray tags like this. A parameter for BaseParser like `drop_stray_tags` or some overridable method would be quite straightforward.

**Comment by holub008** [comment]
Seemingly the only way to get around this right now is:

```
import rispy
from rispy.parser import NextLine, ParseError


class LaxRISParser(rispy.RisParser):
    def is_header(self, line):
        """
        ignore any non-tag junk (e.g. ref counter, search strategy)
        """
        return True

    def _parse_tag(self, line):
        """
        overriding private method so that tags when not in_ref may be NextLined
        """
        tag = self.get_tag(line)
        if tag in self.ignore:
            raise NextLine

        if tag == self.END_TAG:
            return self.current

        if tag == self.START_TAG:
            # New entry
            if self.in_ref:
                raise ParseError(f"Missing end of record tag in line {self.line_number}:\n {line}")
            self._add_tag(tag, line)
            self.in_ref = True
            raise NextLine

        if not self.in_ref:
            raise NextLine  # this used to produce a ParseError

        if tag in self.mapping:
            self._add_tag(tag, line)
            raise NextLine
        elif not self.skip_unknown_tags:
            self._add_unknown_tag(tag, line)
            raise NextLine

        raise NextLine
```

I'd love to have a solution that doesn't involve overriding a private method! Happy to make a PR if there are any suggestions.

**Comment by J535D165** [comment]
What kind of error is raised as C1 is a valid tag? This should work out of the box, isn't it?

**Comment by holub008** [comment]
Yep, I should have clarified, the error looks like: `ParseError: Invalid start tag in line 38`, from [here](https://github.com/MrTango/rispy/blob/d719b24023d136bcf8aa46ae34a90b3829e02a5c/rispy/parser.py#L185C32-L185C57). I agree, there's practically no reason this is useful, unless it were more widely adopted. My suspicion is Ovid added it for a specific customer or platform (perhaps another one of their own)

I have limited contacts at Wolters Kluwer, none technical. My business is not a customer of WK (only our customers), so it's an awkward inquiry. Given that other ref management softwares handle this scenario elegantly (ignoring the tag), it feels appropriate for rispy to do the same.

**Comment by shapiromatron** [comment]
Would it make sense to have some preprocessing script that removes all the non-valid RIS lines instead? I'm a little hesitant to add to `rispy` b/c it sounds like this file isn't really compliant with the RIS spec.

**Comment by holub008** [comment]
OK-- I was floating this issue in case this was a common need & I could share a solution with everyone; Ovid is not a small platform, and other ref managers apparently decided this was a worthwhile feature. But, I understand wanting to stick to what is pretty clearly the intended RIS spec. Thanks for the feedback!
